stages:
  - test
  - build
  - deploy

unit-test:
  script:
    C:\"Program Files"\Unity\2020.1.6f1\Editor\Unity.exe -batchmode -projectPath . -runTests -testPlatform playmode -logFile -testResults .\unit-tests.xml | Out-Default
  after_script:
    - '[xml]$xml = Get-Content -PATH .\unit-tests.xml'
    - '$xml.SelectNodes("//test-case") | Format-Table -AutoSize -Property result, name'
  stage: test

unity-build:
  script: C:\"Program Files"\Unity\2020.1.6f1\Editor\Unity.exe -batchmode -projectPath . -buildWindowsPlayer C:/Gitlab-Runner/builds/buildpath/assignment-2-automated-testing.exe -logfile C:/Gitlab-Runner/builds/buildpath/buildlog.log -quit | Out-Default
  stage: build

playstore:
  script: "echo 'Deploying...'"
  stage: deploy
