stages:
  - test
  - build
  - deploy

unit-test:
  script:
    - dir 
    - C:\"Program Files"\Unity\2020.1.6f1\Editor\Unity.exe -batchmode -projectPath . -runTests -testPlatform playmode -logFile -testResults .\unit-tests.xml | Out-Default
  after_script:
      - '[xml]$xml = Get-Content -PATH .\unitTests.xml'
      - '$xml.SelectNodes("//test-case") | Format-Table -AutoSize -Property result, name'
  stage: test

unity-build:
  script: "echo 'Building...'"
  stage: build

playstore:
  script: "echo 'Deploying...'"
  stage: deploy
