stages:
  - test
  - build
  - deployunit-test:
  stage: test
  script: echo 'Testing...'unity-build:
  stage: build
  script: echo 'Building...'playstore:
  stage: deploy
  script: echo 'Deploying...'