stages:
  - test
  - build
  - deploy

unit-test:
  script: 'C:\Program Files\Unity\2020.1.6f1\Editor \
    -batchmode \
    -projectPath . \
    -runTests -testPlatform editmode \
    -logFile \
    -testResults ./unit-tests.xml'
  stage: test

unity-build:
  script: "echo 'Building...'"
  stage: build

playstore:
  script: "echo 'Deploying...'"
  stage: deploy
